FROM nvcr.io/nvidia/pytorch:25.10-py3

ENV DEBIAN_FRONTEND=noninteractive
ENV DEBCONF_NONINTERACTIVE_SEEN=true

# Install system dependencies
RUN apt-get update && apt-get install -y \
    git \
    wget \
    vim \
    && rm -rf /var/lib/apt/lists/*

# Upgrade pip
RUN pip install --no-cache-dir --upgrade pip

# Install Python dependencies
RUN pip install lightning==2.5.6 \
        transformers==4.57.1 \
        datasets==4.4.1 \
        peft==0.18.0 \
        accelerate==1.12.0 \
        tensorboard==2.20.0 \
        sentencepiece==0.2.1 \
        torchao==0.14.1 \
        wandb==0.23.0 \
        vllm==0.12.0 \
        mpi4py==4.1.1

RUN pip install bert-score==0.3.13
RUN pip install evaluate==0.4.6


# Keeps Python from generating .pyc files in the container
ENV PYTHONDONTWRITEBYTECODE=1

# Turns off buffering for easier container logging
ENV PYTHONUNBUFFERED=1

WORKDIR /app
