services:
  server_0:
    image: ${IMAGE}
    command: ${COMMAND}
    environment:
      - MODEL_ID=${MODEL_ID}
      - HF_HOME=/snapshots/huggingface
      - HF_TOKEN=${HF_TOKEN}
      - MAX_MODEL_LEN=${MAX_MODEL_LEN}
      - OMP_NUM_THREADS=16
      - TENSOR_PARALLEL_SIZE=${TENSOR_PARALLEL_SIZE}
      - MAX_NUM_SEQS=${MAX_NUM_SEQS}
    devices:
     - /dev/neuron0:/dev/neuron0
    shm_size: 32Gb
    volumes:
      - ${HOME}/scripts/djl-lmi:/scripts:ro
      - ${HOME}/cache:/cache:rw
      - ${HOME}/snapshots:/snapshots:rw
    ports:
      - "8080:8080"
     

  