services:
  server_0:
    image: ${IMAGE}
    command: ${COMMAND}
    environment:
      - MODEL_ID=${MODEL_ID}
      - HF_HOME=/snapshots/huggingface
      - HF_TOKEN=${HF_TOKEN}
      - MAX_MODEL_LEN=${MAX_MODEL_LEN}
      - OMP_NUM_THREADS=16
      - TENSOR_PARALLEL_SIZE=${TENSOR_PARALLEL_SIZE}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 8
              capabilities: [gpu]
    shm_size: 32Gb
    volumes:
      - ${HOME}/scripts/djl-lmi:/scripts:ro
      - ${HOME}/snapshots:/snapshots:rw
    ports:
      - "8080:8080"