services:
  server_0:
    image: ${IMAGE}
    command: ${COMMAND}
    environment:
      - MODEL_ID=${MODEL_ID}
      - HF_HOME=/snapshots/huggingface
      - HF_TOKEN=${HF_TOKEN}
      - OMP_NUM_THREADS=16
      - MAX_MODEL_LEN=${MAX_MODEL_LEN}
      - TENSOR_PARALLEL_SIZE=${TENSOR_PARALLEL_SIZE}
      - MAX_NUM_SEQS=${MAX_NUM_SEQS}
      - NEURON_CONTEXT_LENGTH_BUCKETS=${NEURON_CONTEXT_LENGTH_BUCKETS}
      - NEURON_TOKEN_GEN_BUCKETS=${NEURON_TOKEN_GEN_BUCKETS}
    devices:
     - /dev/neuron0:/dev/neuron0
    volumes:
      - ${HOME}/scripts/triton:/scripts:ro
      - ${HOME}/snapshots:/snapshots:rw
      - ${HOME}/cache:/cache:rw
    ports:
      - "8080:8080"