services:
  server_0:
    image: ${IMAGE}
    command: ${COMMAND}
    environment:
      - MODEL_ID=${MODEL_ID}
      - HF_HOME=/snapshots/huggingface
      - HF_TOKEN=${HF_TOKEN}
    devices:
     - /dev/neuron0:/dev/neuron0
     - /dev/neuron1:/dev/neuron1
     - /dev/neuron2:/dev/neuron2
     - /dev/neuron3:/dev/neuron3
     - /dev/neuron4:/dev/neuron4
     - /dev/neuron5:/dev/neuron5
     - /dev/neuron6:/dev/neuron6
     - /dev/neuron7:/dev/neuron7
     - /dev/neuron8:/dev/neuron8
     - /dev/neuron9:/dev/neuron9
     - /dev/neuron10:/dev/neuron10
     - /dev/neuron11:/dev/neuron11
     - /dev/neuron12:/dev/neuron12
     - /dev/neuron13:/dev/neuron13
     - /dev/neuron14:/dev/neuron14
     - /dev/neuron15:/dev/neuron15
    shm_size: 32Gb
    volumes:
      - ${HOME}/scripts/triton:/scripts:ro
      - ${HOME}/snapshots:/snapshots:rw
      - ${HOME}/cache:/cache:rw
    ports:
      - "8080:8080"