endpoint_url: "http://localhost:8080/v2/models/model/generate"
module_name: "llama3_prompt_generator"
module_dir: "modules/inst-semeval2017"
prompt_generator: "PromptGenerator"
kwargs:
  sampling_parameters: "{ \"top_k\": 50, \"max_new_tokens\": 2048, \"do_sample\": true }"